# Generated by Django 5.0.6 on 2024-06-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_userprofile_full_name_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fullname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
