# Generated by Django 5.0.6 on 2024-06-15 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_userprofile_username_userprofile_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
    ]
