# Generated by Django 5.0.6 on 2024-06-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_post_lim_alter_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AlterField(
            model_name='post',
            name='lim',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=20),
        ),
    ]
