# Generated by Django 5.0.6 on 2024-06-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='from_user',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='to_user',
            field=models.CharField(max_length=150),
        ),
    ]
