# Generated by Django 5.0.6 on 2024-06-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_post_lim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lim',
            field=models.CharField(choices=[('new', 'new'), ('yes', 'Yes'), ('no', 'No')], default='new', max_length=20),
        ),
    ]
