# Generated by Django 5.0.6 on 2024-06-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_type',
            field=models.CharField(choices=[('post', 'Post'), ('location', 'Location'), ('gallery', 'Gallery'), ('video', 'Video')], default='', max_length=20),
        ),
    ]
