# Generated by Django 5.0.6 on 2024-06-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_comment_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
