# Generated by Django 5.0.6 on 2024-06-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='receiver_image',
        ),
    ]
